### ISSUE TITLE
[Feat] 환율 변동 프로그램

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#17]
## 📌  Feature Issue
연산 프로퍼티와 프로퍼티 옵저버를 활용한 환율 변동 프로그램을 구현합니다.

## 📝  To-do
- [x] 연산 프로퍼티 활용
- [x] 프로퍼티 옵저버 활용
- [x] 환율 로직 구현
