### ISSUE TITLE
[Feat] 0802 수업 및 과제

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#23]
## 📌  Feature Issue
네트워크 통신 관련 개념 정리 및 실습을 구현합니다.

## 📝  To-do
- [x] 네트워크 통신 개념 복습
- [x] 영화 API (GET) 실습 
- [x] 영화 응답 데이터 모델 
- [x] 네이버 번역 API (POST) 실습
- [x] 오류 코드 분기처리
- [ ] Lottery API 구현 - 가장 최근 회차로 
- [x] 영화 API 구현 - 항상 어제 날짜값을 기준으로 GET
- [x] 번역 API - 버튼 눌렀을 때
- [x] Beer API 구현

**Comment by pcsoyeon** [comment]
### REST API

**REST API의 6원칙**
가장 중요한 두 가지 원칙은 비연결성, 무상태성 

1. 비연결성
클라이언트의 요청 시에만 서버에서 응답이 오는 구조로, 할 일이 끝나면 연결이 해제
2. 무상태성
기본적으로 클라이언트를 구분할 수 없음
(그래서 웹에서는 쿠키/세션을 통해서, 앱에서는 토큰을 통해서 클라이언트를 구분)
3. Cashable
캐싱 기능을 활용할 수 있음
4. Self-Descriptiveness
URL만 보아도, 어떤 의도로/어떤 자원을 관리하는 지 알 수 있어야 함 
5. Client-Server
클라이언트가 서버에 요청을 할 때에만, 서버에서 응답을 줌
(서버가 클라이언트의 요청 없이 응답을 줄 수 없음)
6. 계층형 구조

**REST API의 장/단점**
장점 : 특정 언어 및 기술에 종속되어 있지 않음
단점 : Overfatching / Underfatching / 과도한 Endpoint
