### ISSUE TITLE
[Feat] 0803 수업 및 과제

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#24]
## 📌  Feature Issue
0803 수업 및 과제 코드를 작성합니다. 

## 📝  To-do
- [x] TMDB 프로젝트 초기 설정 (폴더링 및 초기 파일 추가)
- [x] .gitignore 파일 추가 
- [x] TMDB UI 및 서버통신 구현
- [x] 네이버 이미지 서버통신
- [ ] UISearchController 
- [ ] Multiple Trailing Closure

**Comment by pcsoyeon** [comment]
"yyyy" 와 "YYYY" 의 차이점이 무엇인가?

**Comment by pcsoyeon** [comment]
페이지네이션의 2가지 방식 그리고 차이점?

**Comment by pcsoyeon** [comment]
서버 통신 할 때, 한글을 URL에 함께 보낼 시 주의할 점

**Comment by pcsoyeon** [comment]
타입 어노테이션과 타입 추론의 비교
