### ISSUE TITLE
[Feat] 0804 수업 및 과제

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#25]
## 📌  Feature Issue
0804 수업 및 과제 코드를 작성합니다. 

## 📝  To-do
- [x] 로딩 UI 구현
- [x] 페이지네이션 구현 
- [x] UISearchBar로 검색 구현 
- [x] TMDB 페이지네이션
- [x] TMDB 상세 화면

**Comment by pcsoyeon** [comment]
**_이미지 URL의 경우 어떻게 받아오는 것이 좋을까?_**
- 서버 통신하는 과정에서 (= URL을 받아오는 과정에서) String 배열이 아닌 URL로 변환
- 또는 UIImage 배열로 받아올 수 있다.

그러나, 서버 통신 과정에서 URL -> UIImage까지 처리하면 오래 걸릴 수 있다.

셀에서 작업을 할 수도 있는데(= 셀에서 서버 통신) 이는, 셀에게 많은 작업을 넘기기 때문에 권장하지 않는다.

**Comment by pcsoyeon** [comment]
**_Xib 파일에서 왼쪽 상단으로 레이아웃이 맞춰지는 경우_**
버그일 확률이 높기 때문에 아쉽지만 Xib 파일을 삭제하고 다시 만드는 것이 딥이다 ..

**Comment by pcsoyeon** [comment]
**_Serialization_** 
직렬화 (<-> 역직렬화)
