### ISSUE TITLE
[Feat] 0805 수업 및 과제 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#26]
## 📌  Feature Issue
0805 수업 및 과제 코드를 작성합니다. 

## 📝  To-do
- [x] 0804 TIL Github에 짧게 정리
- [ ] 일급 객체 / 클로저 (문법)
- [x] 네트워크 코드 개선
