### ISSUE TITLE
[Feat] 0808 수업 및 과제 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#27]
## 📌  Feature Issue
0808 수업 및 과제 코드를 작성합니다. 

## 📝  To-do
- [x] Kakao 검색 API 구현
- [x] APIManger로 코드 분리
- [x] 클로저 활용
- [x] UITableView + 심화
- [x] TMDB - API EndPoint 리펙토링
- [ ] TMDB - expandable cell 구현
