### ISSUE TITLE
[Feat] 0809 수업 및 과제

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#28]
## 📌  Feature Issue
0809 수업 및 과제 코드를 작성합니다.

## 📝  To-do
- [x] @IBInspectable / @IBDesignable
- [x] Swift Attribute
- [x] Xib 파일로 UI 구현
- [x] UITableViewCell, UICollectionViewCell 중첩 구조 구현
- [x] TMDB - 셀 중첩 구조 UI 구현
- [x] TMDB - 헤더뷰 UI 구현
