### ISSUE TITLE
[Refactor] TMDB 코드 개선

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#32]
## 📌  Feature Issue
수업시간에 배운 내용을 바탕으로 TMDB 프로젝트 코드를 개선합니다. 

## 📝  To-do
- [x] 네트워크 코드 개선
- [ ] Access Control 작성 
- [ ] GET 이외의 API 연결
- [ ] TMDB - expandable cell 구현 
- [ ] TMDB - SkeletonView 적용

**Comment by pcsoyeon** [comment]
TMDB 프로젝트 다른 레포로 이동합니다 ~
