### ISSUE TITLE
[Feat] ShoppingList + Realm

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#37]
## 📌  Feature Issue
Shopping List UI/레이아웃 구현 및 Realm로 Database 구축 

## 📝  To-do
- [x] 초기세팅
- [x] UI/레이아웃 구현 
- [x] Realm 데이터베이스 구축
- [x] CRUD 구현 
- [x] 필터 구현
- [x] 정렬 구현
- [x] 상세 화면으로 데이터 전달
