### ISSUE TITLE
[Feat] Shopping List + File Manager 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#39]
## 📌  Feature Issue
File Manager를 이용해서 Shopping List 백업/복구 기능을 구현합니다. 

## 📝  To-do
- [ ] 백업 기능 구현
- [ ] 백업 리스트 구현
- [ ] 이미지 백업 기능 구현 
- [ ] 복구 기능 구현
