### ISSUE TITLE
[Feat] 0719 과제

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Three#7]
## 📌  Feature Issue
0719 과제를 구현합니다. (쇼핑 목록 리스트 및 트렌드 미디어 검색 화면)

## 📝  To-do
- [x] 쇼핑 목록 리스트
- [x] 트렌드 미디어 검색 화면
- [ ] Property Wrapper 정리
